export interface MachineAssistedKoreanGlossOverride {
  englishDescription: string
  meaningKo: string
}

/**
 * The pinned translation model treats dictionary cross-references such as
 * "same as wake" as literal prose and produces unusable Korean. These exact,
 * phrase-and-description-scoped replacements are machine-assisted editorial
 * drafts, not human-reviewed translations. They are used only while proposing
 * schema-v4 candidates in `.content-cache`; the release builder reads the
 * exhaustive schema-v5 registry as its single canonical source of truth.
 */
export const MACHINE_ASSISTED_SAME_AS_GLOSSES: Readonly<
  Record<string, MachineAssistedKoreanGlossOverride>
> = {
  'wake up': { englishDescription: 'same as wake', meaningKo: '깨우다; 정신을 차리게 하다' },
  'knock over': { englishDescription: 'same as knock down', meaningKo: '쳐서 넘어뜨리다' },
  'open up': { englishDescription: 'same as open', meaningKo: '새로 문을 열다; 개장하다' },
  'cut across': { englishDescription: 'same as cut', meaningKo: '가로질러 가다' },
  'cut out': { englishDescription: 'same as cut', meaningKo: '잘라 내다' },
  'lie down': { englishDescription: 'same as lie', meaningKo: '눕다' },
  'get about': { englishDescription: 'same as get around', meaningKo: '여기저기 이동하다' },
  'get round': { englishDescription: 'same as get around', meaningKo: '법이나 규정을 피해 가다' },
  'put by': { englishDescription: 'same as put aside', meaningKo: '돈을 따로 모아 두다' },
  'let into': { englishDescription: 'same as let', meaningKo: '비밀을 알려 주다' },
  'step down': { englishDescription: 'same as step', meaningKo: '직위에서 물러나다' },
  'close down': { englishDescription: 'same as close', meaningKo: '사업장이나 시설의 운영을 중단하다' },
  'key in': { englishDescription: 'same as key', meaningKo: '키보드로 입력하다' },
  'stir up': { englishDescription: 'same as stir', meaningKo: '감정이나 관심을 불러일으키다' },
  'split up': { englishDescription: 'same as split', meaningKo: '헤어지다; 결별하다' },
  'straighten out': { englishDescription: 'same as straighten', meaningKo: '문제나 혼란을 바로잡다' },
  'flare up': { englishDescription: 'same as flare', meaningKo: '갑자기 다시 불붙거나 격해지다' },
  'mop up': { englishDescription: 'same as mop', meaningKo: '액체를 닦아 내다' },
  'tease out': { englishDescription: 'same as tease', meaningKo: '조심스럽게 풀거나 분리해 내다' },
  'tidy up': { englishDescription: 'same as tidy', meaningKo: '정리하다; 말끔히 다듬다' },
  'land up': { englishDescription: 'same as land', meaningKo: '결국 어떤 곳이나 상황에 이르다' },
  'catch out': { englishDescription: 'same as catch', meaningKo: '실수나 거짓을 들춰내다' },
  'lay up': { englishDescription: 'same as lay', meaningKo: '병이나 부상으로 누워 지내다' },
  'fold up': { englishDescription: 'same as fold', meaningKo: '사업이나 프로젝트를 접다' },
  'stack up': { englishDescription: 'same as stack', meaningKo: '차곡차곡 쌓다' },
  'cough up': { englishDescription: 'same as cough', meaningKo: '마지못해 돈을 내놓다' },
  'foul up': { englishDescription: 'same as foul', meaningKo: '일을 망치거나 작동을 방해하다' },
  'ladle out': { englishDescription: 'same as ladle', meaningKo: '국자로 떠서 나누어 주다' },
  'get onto': { englishDescription: 'same as get on', meaningKo: '방송이나 위원회 등에 들어가다' },
  'get on': { englishDescription: 'same as get along', meaningKo: '사람들과 잘 지내다' },
  'come around': { englishDescription: 'same as come', meaningKo: '때나 기회가 돌아오다' },
  'turn back': { englishDescription: 'same as turn down', meaningKo: '가던 길을 되돌아가다' },
  'turn to': { englishDescription: 'same as turn', meaningKo: '어려울 때 도움을 청하다' },
  'play around': { englishDescription: 'same as play', meaningKo: '이리저리 놀다' },
  'buy off': { englishDescription: 'same as buy', meaningKo: '돈으로 매수해 입막음하다' },
  'serve out': { englishDescription: 'same as serve', meaningKo: '정해진 기간을 끝까지 채우다' },
  'stay back': { englishDescription: 'same as stay', meaningKo: '뒤에 남다' },
  'cut back': { englishDescription: 'same as cut down', meaningKo: '사용량이나 지출을 줄이다' },
  'free up': { englishDescription: 'same as free', meaningKo: '자금이나 자원에 여유를 만들다' },
  'hit upon': { englishDescription: 'same as hit on', meaningKo: '우연히 생각해 내거나 찾아내다' },
  'throw out': { englishDescription: 'same as throw away', meaningKo: '필요 없는 것을 버리다' },
  'fill in': { englishDescription: 'same as fill', meaningKo: '빈칸이나 빈 공간을 채우다' },
  'drop away': { englishDescription: 'same as drop', meaningKo: '지면이 갑자기 아래로 낮아지다' },
  'drop back': { englishDescription: 'same as drop', meaningKo: '뒤로 처지다' },
  'drop off': { englishDescription: 'same as drop', meaningKo: '사람을 내려 주거나 물건을 갖다 놓다' },
  'save up': { englishDescription: 'same as save', meaningKo: '돈을 모으다' },
  'hang about': { englishDescription: 'same as hang', meaningKo: '특별한 일 없이 머물거나 지체하다' },
  'hang out': { englishDescription: 'same as hang', meaningKo: '친구들과 어울려 시간을 보내다' },
  'finish off': { englishDescription: 'same as finish', meaningKo: '남은 것을 마저 끝내다' },
  'finish up': { englishDescription: 'same as finish', meaningKo: '마무리하다' },
  'trip up': { englishDescription: 'same as trip', meaningKo: '발이 걸려 넘어지다' },
  'camp out': { englishDescription: 'same as camp', meaningKo: '야외에서 야영하다' },
  'roll out': { englishDescription: 'same as roll', meaningKo: '펼치거나 밀어 펴다' },
  'lift up': { englishDescription: 'same as lift', meaningKo: '들어 올리거나 높이다' },
  'blow out': { englishDescription: 'same as blow', meaningKo: '불어서 불을 끄다' },
  'cool down': { englishDescription: 'same as cool', meaningKo: '식혀 온도를 낮추다; 식다' },
  'hire out': { englishDescription: 'same as hire', meaningKo: '돈을 받고 빌려 주다' },
  'connect up': { englishDescription: 'same as connect', meaningKo: '서로 연결하다' },
  'empty out': { englishDescription: 'same as empty', meaningKo: '내용물을 완전히 비우다' },
  'mark off': { englishDescription: 'same as mark out', meaningKo: '경계를 표시해 구획하다' },
  'slow down': { englishDescription: 'same as slow', meaningKo: '속도나 활동을 늦추다' },
  'separate out': { englishDescription: 'same as separate', meaningKo: '분리해 내거나 구별하다' },
  'divide up': { englishDescription: 'same as divide', meaningKo: '여러 몫이나 집단으로 나누다' },
  'knock up': { englishDescription: 'same as knock', meaningKo: '급히 만들어 내다' },
  'lock up': { englishDescription: 'same as lock away', meaningKo: '안전하게 잠가 두다' },
  'toss up': { englishDescription: 'same as toss', meaningKo: '동전을 던져 결정하다' },
  'mount up': { englishDescription: 'same as mount', meaningKo: '쌓여 늘어나다' },
  'pile up': { englishDescription: 'same as pile', meaningKo: '쌓아 올리다' },
  'ease up': { englishDescription: 'same as ease off', meaningKo: '압박이나 강도를 완화하다' },
  'chop up': { englishDescription: 'same as chop', meaningKo: '잘게 썰다' },
  'chill out': { englishDescription: 'same as chill', meaningKo: '긴장을 풀고 진정하다' },
  'spy out': { englishDescription: 'same as spy', meaningKo: '둘러보며 찾아내다' },
  'brighten up': { englishDescription: 'same as brighten', meaningKo: '밝아지거나 밝게 만들다' },
  'buckle up': { englishDescription: 'same as buckle', meaningKo: '안전벨트를 매다' },
  'choke down': { englishDescription: 'same as choke', meaningKo: '억지로 삼키다' },
  'chuck away': { englishDescription: 'same as chuck', meaningKo: '내다 버리다' },
  'polish up': { englishDescription: 'same as polish', meaningKo: '다듬어 향상시키다' },
  'drop behind': { englishDescription: 'same as drop back', meaningKo: '뒤처지다' },
  'rise up': { englishDescription: 'same as rise', meaningKo: '일어서거나 위로 오르다' },
  'check over': { englishDescription: 'same as check', meaningKo: '꼼꼼히 점검하다' },
  'block up': { englishDescription: 'same as block', meaningKo: '막아 버리다' },
  'rain down': { englishDescription: 'same as rain', meaningKo: '비처럼 쏟아지다' },
  'mark as': { englishDescription: 'same as mark', meaningKo: '특정한 유형으로 표시하다' },
  'spin round': { englishDescription: 'same as spin', meaningKo: '빙글 돌리다; 몸을 홱 돌리다' },
}
