import type { PhrasalVerbItem } from './types'

/**
 * Concise, reader-facing corrections for source glosses whose intended sense is
 * sound but whose machine translation is too literal or structurally unclear.
 * The canonical catalog and its provenance remain unchanged; these labels are
 * deliberately scoped to the reading experience.
 */
const READER_GLOSS_CORRECTIONS: Readonly<Record<string, string>> = {
  'add to': '무언가를 더해 양이나 수를 늘리다',
  'branch off': '큰길이나 중심 부분에서 갈라져 나가다',
  'camp out': '야외에서 텐트를 치고 지내다',
  'come about': '특히 우연히 어떤 일이 생기다',
  'come away': '경험 뒤에 특정 생각이나 느낌을 갖게 되다',
  'come up': '행사나 일이 곧 다가오다',
  'connect up': '기기나 부품을 서로 연결하다',
  'end in': '마지막에 특정한 결과로 이어지다',
  'fall about': '웃음을 참지 못하고 크게 웃다',
  'fall down': '옷이 헐거워 아래로 흘러내리다',
  'fall in': '지붕이나 벽이 무너져 내리다',
  'fall off': '양·수준·가치가 줄어들다',
  'finish up': '여러 일을 거친 끝에 특정 장소나 상태에 이르다',
  'get off': '일을 마치고 직장에서 나오다',
  'go in': '설명이나 정보가 머리에 들어와 이해되다',
  'pull over': '차량을 길가에 세우다',
  'remind of': '비슷한 사람이나 일을 떠올리게 하다',
  'report back': '돌아와 결과나 상황을 알리다',
  'run to': '금액이나 수량이 특정 수준에 이르다',
  'sleep through': '어떤 일이 일어나는 동안 깨지 않고 계속 자다',
  'stay down': '먹은 음식이 탈 없이 위에 남아 있다',
  'stay off': '줄어든 체중이 다시 늘지 않다',
  'take over': '일이나 책임을 넘겨받아 맡다',
  'throw up': '뜻밖의 문제나 결과를 만들어 내다',
  'tie up': '일을 끝내기 전에 남은 부분을 처리하다',
  'trip up': '실수하게 만들거나 일을 방해하다',
  'turn in': '잘못한 사람을 경찰에 넘기다',
  'wash off': '물이나 세탁으로 표면의 때를 씻어 내다',
  'wash out': '천에 묻은 얼룩을 씻어 내다',
  'wipe out': '천으로 용기나 물건의 안쪽을 닦다',
  'wrap round': '천이나 끈 등을 다른 것의 둘레에 감다',
  'account for': '돈이 어디에 어떻게 쓰였는지 설명하다',
  'base on': '사실이나 근거를 바탕으로 하다',
  'bring out': '숨은 성질이나 특징이 드러나게 하다',
  'carry over': '한 기간의 돈이나 권리를 다음 기간으로 넘기다',
  'deal with': '문제나 상황에 대처하다',
  'draw up': '문서나 계획을 작성하다',
  'fall through': '계획이나 합의가 무산되다',
  'figure out': '이해하거나 해결 방법을 찾아내다',
  'hold back': '감정이나 반응을 드러내지 않고 억누르다',
  'iron out': '남은 문제나 의견 차이를 해결하다',
  'look into': '문제의 사실관계를 조사하다',
  'map out': '과정이나 계획을 자세히 짜다',
  'play down': '실제보다 덜 중요하거나 심각해 보이게 하다',
  'root out': '나쁘거나 불법적인 것을 찾아 없애다',
  'send in': '서류나 자료를 기관에 제출하다',
  'set down': '손에 든 것을 내려놓다',
  'size up': '사람이나 상황을 살펴 판단하다',
  'sort out': '문제나 혼란을 해결하다',
  'sound out': '대화를 통해 의견이나 태도를 알아보다',
  'start out': '처음에는 특정 모습이나 상태로 시작하다',
  'sum up': '사건이나 논의의 핵심을 요약하다',
  'back down': '반대에 부딪혀 요구나 주장을 거두다',
  'back off': '위험하거나 불편한 대상에서 뒤로 물러나다',
  'back out': '약속이나 합의에서 빠지다',
  'bear out': '사실이 맞음을 뒷받침하다',
  'bear with': '잠시 참고 기다려 달라고 부탁하다',
  'believe in': '누군가나 무언가가 존재한다고 믿다',
  'bottle up': '감정을 드러내지 않고 억누르다',
  'brighten up': '날씨나 하늘이 밝아지다',
  'brush off': '상대의 말이나 중요성을 무시하다',
  'buy out': '공동 소유자의 지분을 사들이다',
  'call in': '전문가나 서비스 인력을 불러 문제를 처리하게 하다',
  'catch out': '준비하지 못한 상황에서 곤란하게 하다',
  'check in': '호텔이나 병원에 도착해 등록하다',
  'check into': '호텔이나 병원에 도착해 등록하다',
  'claw back': '잃었던 돈을 세금이나 요금 등으로 되찾다',
  'come across': '특정한 인상을 주다',
  'come apart': '낡거나 약해져 여러 조각으로 분리되다',
  'come off': '말도 안 된다고 핀잔주다',
  'come on': '교체 선수로 경기장에 들어오다',
  'cover up': '사실이나 잘못을 숨기다',
  'cover for': '누군가가 자리를 비운 동안 그 일을 대신하다',
  'dig out': '파서 물건을 꺼내다',
  'do in': '누군가를 몹시 지치게 하다',
  'drag on': '바라는 것보다 오래 끌다',
  'drag up': '잊고 싶은 과거 일을 다시 꺼내다',
  'fear for': '누군가의 안전이나 안부를 걱정하다',
  'fill up': '음식을 충분히 먹어 배부르게 하다',
  'fit in': '집단에 자연스럽게 어울려 받아들여지다',
  'fix on': '눈이나 시선을 누군가나 무언가에 고정하다',
  'fob off': '불완전한 답변이나 물건으로 얼버무리다',
  'follow up': '더 알아보거나 후속 조치를 하다',
  'get over': '나쁜 일을 겪은 뒤 회복하다',
  'get past': '승인권자의 심사를 통과하다',
  'get together': '사람들이 만나 함께 시간을 보내다',
  'hear from': '누군가에게서 연락이나 소식을 받다',
  'hold on': '잠시 기다리다',
  'go against': '결정이나 판결이 누군가에게 불리하게 나다',
  'go out': '유행이 지나다',
  'laugh off': '농담으로 넘겨 대수롭지 않게 여기다',
  'line up': '다른 것과 나란히 맞추다',
  'lock into': '쉽게 벗어날 수 없는 체계나 계획에 묶다',
  'look out': '위험하지 않도록 조심하라고 경고하다',
  'look over': '빠르게 살펴보거나 점검하다',
  'make up': '다툰 뒤 화해하다',
  'make over': '외모나 모습을 바꾸거나 개선하다',
  'mix up': '둘 이상의 사람이나 사물을 서로 혼동하다',
  'muddle along': '뚜렷한 계획 없이 그럭저럭 이어 가다',
  'pair off': '짝을 이루거나 연인이 되다',
  'phone back': '다시 전화하다',
  'pick up': '바닥이나 낮은 곳에 있는 것을 들어 올리다',
  'play along': '목적을 위해 동의하는 척하다',
  'plan on': '무언가를 할 생각이거나 그렇게 될 것으로 예상하다',
  'pull out': '차량이 차선이나 도로로 진입하다',
  'push forward': '반대나 어려움에도 앞으로 나아가다',
  'put across': '생각이나 사람됨을 분명하고 효과적으로 전달하다',
  'put over': '사실이 아닌 것을 믿도록 속이다',
  'rake up': '잊고 싶은 과거 일을 다시 꺼내다',
  'rest with': '결정이나 책임이 누군가에게 있다',
  'run away': '머물던 곳에서 몰래 달아나다',
  'run down': '누군가를 부당하게 깎아내리다',
  'run out': '다 써서 남은 것이 없게 되다',
  'see about': '일을 처리하거나 준비하다',
  'see around': '자주 다니는 곳에서 누군가를 종종 마주치다',
  'seek out': '작정하고 찾아내다',
  'set aside': '나중에 쓰려고 일부를 따로 보관하다',
  'sign away': '서명해 재산이나 권리를 넘기다',
  'slow down': '속도나 활동을 늦추다',
  'speak out': '공개적으로 분명히 의견을 말하다',
  'spy out': '둘러보며 찾아내다',
  'stand back': '감정과 거리를 두고 상황을 객관적으로 보다',
  'stand for': '선거에 출마하다',
  'start in': '불평이나 비난을 장황하게 시작하다',
  'stay back': '앞으로 가지 않고 뒤에 머물다',
  'stick around': '무언가를 기다리며 더 오래 머물다',
  'store up': '나중에 쓰려고 많이 모아 두다',
  'take in': '듣거나 읽은 내용을 이해하고 기억하다',
  'take to': '무언가를 습관으로 시작하다',
  'talk back': '윗사람에게 말대꾸하다',
  'talk round': '설득해 동의하게 하다',
  'top up': '필요한 수준이 되도록 더 채우다',
  'trust to': '다른 방법이 없어 운이나 우연에 기대다',
  'try out': '적합하거나 효과적인지 시험해 보다',
  'turn back': '가던 길을 되돌아가거나 되돌리다',
  'turn off': '기계나 전원을 끄다',
  'turn over': '누운 몸을 반대쪽으로 돌리다',
  'walk around': '눈에 띄는 모습이나 행동으로 돌아다니다',
  'warm up': '따뜻해지거나 따뜻하게 하다',
  'watch out': '위험을 피하도록 조심하다',
  'watch over': '보호하거나 책임지고 지켜보다',
  'wear out': '누군가를 몹시 지치게 하다',
  'allow of': '어떤 가능성이나 여지를 허용하다',
  'attend to': '손님이나 필요한 일을 살펴 돌보다',
  'bite back': '화가 나서 말이나 행동으로 맞받아치다',
  'brew up': '차 같은 따뜻한 음료를 만들다',
  'bring about': '어떤 일이나 변화를 일으키다',
  'bring along': '어딘가에 갈 때 함께 가져오다',
  'bring on': '질병이나 문제를 일으키다',
  'buy up': '많은 양이나 남은 물량을 모두 사들이다',
  'call away': '급한 일 때문에 떠나도록 부르다',
  'call up': '누군가에게 전화하다',
  'clear out': '사람이나 물건을 모두 내보내 비우다',
  'come from': '어떤 곳에서 오거나 비롯되다',
  'come over': '감정이나 기분이 갑자기 밀려오다',
  'come together': '공동의 목적을 위해 한자리에 모이다',
  'come under': '압박이나 비판 같은 일을 겪다',
  'conk out': '피곤해서 갑자기 잠들다',
  'cool off': '화나거나 흥분한 감정이 누그러지다',
  'cough up': '내키지 않지만 돈을 내놓다',
  'count out': '물건을 하나씩 세어 나누다',
  'cross off': '끝낸 항목을 목록에서 줄을 그어 지우다',
  'cut through': '길을 내며 가로질러 통과하다',
  'decide on': '여러 선택지 가운데 하나를 정하다',
  'dress up': '특별한 옷이나 의상을 차려입다',
  'dream up': '새롭거나 특이한 생각을 떠올리다',
  'draw on': '필요한 돈·경험·자원을 꺼내 활용하다',
  'fall for': '속임수나 거짓말을 사실로 믿다',
  'follow through': '시작한 일이나 약속을 끝까지 해내다',
  'get along': '서로 좋아하며 사이좋게 지내다',
  'get into': '학교·과정·조직 등에 들어가다',
  'go towards': '어떤 비용의 일부로 쓰이다',
  'go with': '색이나 모양 등이 서로 잘 어울리다',
  'help out': '일이나 돈을 보태 실질적으로 돕다',
  'invest in': '더 나아지도록 돈이나 자원을 들이다',
  'kick off': '신발을 발로 벗다',
  'know of': '누군가나 무언가의 존재를 알고 있다',
  'land up': '여러 일을 겪은 끝에 어떤 곳이나 상황에 이르다',
  'leave out': '사람이나 내용을 포함하지 않고 빼다',
  'lie back': '몸을 뒤로 기대어 눕다',
  'look back': '과거의 일이나 때를 되돌아보다',
  'look through': '필요한 정보를 찾으려고 빠르게 훑어보다',
  'make off': '잘못을 저지른 뒤 서둘러 달아나다',
  'move in': '다른 사람과 한집에서 살기 시작하다',
  'nod off': '자기도 모르게 깜빡 잠들다',
  'nose around': '정보를 찾으려고 여기저기 기웃거리다',
  'pass out': '더위나 충격 등으로 의식을 잃다',
  'pay up': '미뤄 둔 돈을 마침내 지불하다',
  'phone round': '정보를 얻으려고 여러 곳에 전화하다',
  'plunge into': '어떤 일에 힘차게 뛰어들다',
  'point out': '상대가 알아차리도록 사실을 지적하다',
  'polish off': '음식이나 음료를 남김없이 먹거나 마시다',
  'pour out': '감정이나 걱정을 숨김없이 털어놓다',
  'pull off': '옷을 빠르게 벗다',
  'push for': '원하는 결과를 얻으려고 강하게 요구하다',
  'put aside': '나중에 쓰려고 돈을 따로 모아 두다',
  'put up': '누군가를 자기 집에 잠시 재워 주다',
  'ring round': '정보를 얻거나 일을 정하려고 여러 곳에 전화하다',
  'run for': '선거에서 어떤 직책에 출마하다',
  'screw up': '큰 실수를 하거나 일을 망치다',
  'sell off': '돈을 마련하려고 물건을 빠르게 팔아치우다',
  'sit back': '편히 기대앉아 잠시 쉬다',
  'sleep on': '결정을 미루고 다음 날까지 더 생각하다',
  'sleep over': '다른 사람의 집에서 하룻밤 자다',
  'smooth over': '문제를 덜 심각해 보이도록 얼버무리다',
  'spring from': '어떤 곳이나 원인에서 나오거나 비롯되다',
  'stay away': '가까이 가지 않고 떨어져 있다',
  'step back': '한발 물러나 상황을 전체적으로 바라보다',
  'stick up': '손이나 팔을 위로 들다',
  'stop off': '목적지로 가는 길에 잠시 들르다',
  'stretch out': '몸을 길게 뻗고 눕다',
  'stump up': '내키지 않지만 필요한 돈을 내다',
  'take against': '뚜렷한 이유 없이 싫어하기 시작하다',
  'tear off': '옷을 빠르게 벗어 던지다',
  'tee off': '골프에서 티 위의 공을 쳐 경기를 시작하다',
  'tell off': '잘못한 일을 두고 화내며 꾸짖다',
  'think over': '결정하기 전에 충분히 생각하다',
  'think up': '생각이나 변명을 새로 떠올리다',
  'turn out': '나중에 특정한 사실로 밝혀지다',
  'turn to': '도움을 얻으려고 누군가에게 의지하다',
  'try on': '옷을 입어 보고 모양이나 크기가 맞는지 확인하다',
  'walk off': '알리지 않고 갑자기 자리를 떠나다',
  'weigh down': '무게 때문에 쉽게 움직이지 못하게 하다',
  'while away': '한가한 시간을 느긋하게 보내다',
  'work at': '나아지도록 꾸준히 노력하다',
  'wrap up': '따뜻하도록 옷을 단단히 입다',
  'write out': '내용을 줄이지 않고 완전하게 적다',
  'back up': '차량이 밀려 길게 정체되다',
  'bank on': '어떤 일이 일어날 것이라고 믿고 의지하다',
  'boil away': '액체가 끓어서 증발해 없어지다',
  'bone up': '시험이나 일을 앞두고 열심히 공부하다',
  'bottom out': '가격이나 상황이 가장 낮은 수준에 이르다',
  'bounce back': '어려움을 겪은 뒤 다시 회복하다',
  'bounce off': '빛이나 소리가 표면에 부딪혀 반사되다',
  'break off': '본체에서 부러져 떨어지다',
  'break out': '피부에 발진이나 반점이 생기다',
  'break up': '회의나 모임이 끝나 사람들이 흩어지다',
  'bring over': '사람이나 물건을 상대가 있는 곳으로 데려오다',
  'bring round': '사람이나 물건을 상대의 집으로 데려오다',
  'call at': '다른 곳으로 가는 길에 잠시 들르다',
  'call for': '어떤 조치를 공개적으로 요구하다',
  'carve up': '땅이나 재산을 여러 몫으로 나누다',
  'check on': '안전하거나 잘 지내는지 확인하다',
  'clam up': '당황하거나 비밀을 지키려고 갑자기 입을 다물다',
  'clean out': '안의 물건과 먼지를 모두 치워 깨끗이 비우다',
  'clear away': '다 쓴 물건을 치워 자리를 정돈하다',
  'count on': '도와주거나 해낼 것이라고 믿고 의지하다',
  'crowd out': '더 강한 대상이 다른 대상을 밀어내다',
  'draw out': '편안하게 해 주어 더 많이 말하도록 이끌다',
  'drive away': '불쾌하게 만들어 떠나게 하다',
  'dry off': '표면의 물기를 닦아 말리다',
  'fall behind': '일정이나 다른 사람보다 뒤처지다',
  'fit out': '특정 용도로 쓰도록 방이나 건물에 장비를 갖추다',
  'flesh out': '계획이나 설명에 세부 내용을 보태다',
  'hand down': '옷이나 물건을 다음 세대나 어린 사람에게 물려주다',
  'happen to': '누군가에게 어떤 일이 생기다',
  'keep away': '사람이나 물건이 가까이 오지 못하게 하다',
  'keep from': '누군가가 어떤 일을 하지 못하게 막다',
  'keep in': '벌로 사람을 밖에 나가지 못하게 남겨 두다',
  'kick against': '받아들이기 싫은 결정이나 상황에 저항하다',
  'knock together': '사이의 벽을 없애 두 공간을 하나로 합치다',
  'lay off': '어떤 행동을 잠시 그만두다',
  'look ahead': '앞으로 일어날 일을 생각하고 계획하다',
  'mark out': '특징 때문에 다른 사람과 구별되게 하다',
  'muddle through': '준비나 장비가 부족해도 그럭저럭 해내다',
  'nail down': '합의나 세부 사항을 확실하게 정하다',
  'pan out': '일이나 계획이 특정한 결과로 이어지다',
  'pass to': '소유권이나 통제권이 다른 사람에게 넘어가다',
  'play back': '녹음하거나 촬영한 내용을 다시 재생하다',
  'play out': '사건이나 상황이 특정한 방식으로 전개되다',
  'plough back': '사업에서 난 이익을 다시 그 사업에 투자하다',
  'press ahead': '어려움이나 반대에도 계획을 계속 추진하다',
  'push over': '세게 밀어 넘어뜨리다',
  'push through': '반대에도 법안이나 합의를 통과시키다',
  'read into': '말이나 행동에 실제로 없는 의미까지 찾아내다',
  'rise to': '상대의 도발에 반응하다',
  'see out': '떠나는 손님을 문까지 배웅하다',
  'see through': '어려운 일을 끝까지 계속해 마치다',
  'sell out': '가지고 있던 물건을 모두 팔다',
  'set to': '힘차고 적극적으로 일을 시작하다',
  'settle down': '마음을 가라앉히고 자리를 잡다',
  'shake up': '조직의 운영 방식을 크게 바꾸다',
  'show around': '처음 온 사람에게 곳곳을 안내하다',
  'shut out': '소리나 생각 등이 들어오지 못하게 차단하다',
  'sleep off': '잠을 자서 불쾌한 기분이나 몸 상태를 없애다',
  'soften up': '부드럽게 대해 원하는 일에 동의하도록 만들다',
  'stand in': '다른 사람의 일을 잠시 대신하다',
  'start back': '방학이나 휴식 뒤에 다시 시작하다',
  'stick at': '어렵거나 싫은 일도 포기하지 않고 계속하다',
  'stick out': '일부가 앞으로 튀어나오다',
  'stick to': '정한 방식이나 계획을 바꾸지 않고 지키다',
  'strike off': '힘차게 특정 방향으로 출발하다',
  'sweep up': '빗자루로 먼지나 조각을 쓸어 모으다',
  'swing at': '손이나 도구를 휘둘러 치려고 하다',
  'switch on': '전등이나 기계를 켜다',
  'switch over': '다른 채널이나 시스템으로 바꾸다',
  'talk up': '실제보다 더 좋거나 중요해 보이도록 말하다',
  'think out': '결정하기 전에 중요한 내용을 빠짐없이 생각하다',
  'throw away': '필요 없는 것을 버리다',
  'throw together': '뜻밖의 상황이 사람들을 만나게 하다',
  'tip over': '기울어 옆으로 넘어지다',
  'tune up': '함께 연주하기 전에 악기의 음을 맞추다',
  'turn against': '지지를 거두고 반대하기 시작하다',
  'walk over': '상대를 존중하지 않고 함부로 대하다',
  'watch for': '나타날 때를 놓치지 않도록 주의 깊게 기다리다',
  'wear down': '사용이나 마찰로 조금씩 닳게 하다',
  'work in': '내용이나 생각을 자연스럽게 끼워 넣다',
  'work off': '운동이나 활동으로 감정이나 체중을 줄이다',
  'work on': '생각이나 결정을 바꾸도록 계속 설득하다',
  'stretch to': '당겨져 특정 길이까지 늘어나다',
  'face off': '서로 맞서 경쟁하거나 다투다',
  'wash down': '물로 표면 전체를 씻어 내다',
  'dish up': '음식을 그릇에 담아 내다',
  'brush up': '기술이나 지식을 다시 익혀 향상시키다',
  'set about': '마음먹고 어떤 일을 시작하다',
  'sit through': '지루하거나 불편해도 끝까지 자리를 지키다',
  'end with': '마지막 부분이 특정 내용으로 끝나다',
  'want for': '필요한 것이 부족하다',
  'tell on': '누군가의 잘못을 어른이나 권위자에게 이르다',
  'grow to': '자라서 특정 크기나 높이에 이르다',
  'cut across': '가장자리를 돌지 않고 가로질러 가다',
  'put out': '부탁이나 일로 누군가에게 불편을 끼치다',
  'go up': '가격이나 수치가 오르다',
  'go about': '일이나 문제를 특정한 방식으로 시작해 처리하다',
  'go away': '사람이나 장소에서 떠나다',
  'buy into': '사업의 지분을 사들이다',
  'kick up': '강하게 항의하거나 소란을 일으키다',
  'wear away': '사용이나 마찰로 조금씩 닳아 사라지다',
  'close up': '가게나 조직이 영업을 중단하다',
  'bed down': '누울 곳을 마련해 자게 하다',
  'save on': '비용이나 사용량을 줄이다',
  'answer for': '잘못이나 결과에 책임을 지다',
  'arrive at': '생각이나 검토 끝에 결과에 도달하다',
  'roll out': '말려 있던 것을 평평하게 펼치다',
  'mark off': '선이나 표시로 구역의 경계를 나타내다',
  'serve out': '정해진 기간이 끝날 때까지 직무를 수행하다',
  'serve up': '무언가를 마련해 제공하다',
  'fall apart': '계획이나 관계, 조직이 무너지다',
  'pull together': '여럿이 힘을 합쳐 일을 해내다',
  'act out': '상황이나 사건을 행동으로 재연하다',
  'print out': '컴퓨터 문서를 프린터로 출력하다',
  'lead off': '말이나 행동으로 순서를 시작하다',
  'send down': '잘못을 이유로 대학에서 퇴학시키다',
  'tear away': '하던 일이나 장소에서 억지로 떠나다',
  'freeze out': '누군가를 일이나 모임에서 배제하다',
  'wise up': '상황의 진실을 깨닫다',
  'single out': '여럿 가운데 한 사람을 특별히 지목하다',
  'guard against': '나쁜 일이 생기지 않도록 대비하다',
  'marry up': '두 자료나 부품을 맞춰 연결하다',
  'fit together': '여러 조각이 맞물려 하나를 이루다',
  'shut up': '말을 멈추고 조용히 하다',
  'knock out': '아주 강한 인상을 주어 감탄하게 하다',
  'pack into': '많은 사람이나 물건을 한곳에 채워 넣다',
  'insist on': '반드시 이루어져야 한다고 강하게 요구하다',
  'switch off': '집중을 잃고 더는 귀 기울이지 않다',
  'drag down': '기분을 가라앉히거나 희망을 잃게 하다',
  'occur to': '생각이 갑자기 떠오르다',
  'hang over': '걱정이나 위험이 계속 마음을 누르다',
  'firm up': '계획이나 약속을 더 확실하게 정하다',
  'beat off': '경쟁자를 물리치고 원하는 것을 얻다',
  'slip into': '말이나 내용을 눈에 띄지 않게 끼워 넣다',
  'straighten out': '문제나 혼란을 바로잡아 해결하다',
  'carve out': '노력해 자리나 경력을 만들어 내다',
  'peel off': '젖거나 달라붙은 옷을 벗다',
  'hush up': '입을 다물고 조용히 하다',
  'cast out': '사람을 어떤 곳이나 집단에서 내쫓다',
  'yield to': '결국 상대가 원하는 대로 따르다',
  'rein in': '지나치게 커지거나 이어지는 일을 통제하다',
  'rustle up': '있는 재료로 음식 등을 빨리 마련하다',
  'get round': '법이나 규정을 피해 가다',
  'buy off': '돈을 주어 상대를 매수하다',
  'cut back': '비용이나 지원의 규모를 줄이다',
  'take off': '빠르게 성공하거나 인기를 얻다',
  'blow away': '깊은 인상을 주어 크게 감탄하게 하다',
  'fight back': '공격이나 비난에 맞서 저항하다',
  'hand over': '권한이나 물건을 다른 사람에게 넘기다',
  'bear up': '힘든 상황에서도 용기를 잃지 않고 버티다',
  'move over': '다른 사람이 맡도록 자리나 일을 비켜 주다',
  'ring up': '계산대에 판매 금액을 입력하다',
  'come round': '누군가가 있는 곳에 잠깐 방문하다',
  'get by': '적은 돈이나 자원으로 그럭저럭 지내다',
  'fire up': '누군가를 열정적이거나 흥분하게 만들다',
  'live in': '직장이나 학교가 있는 곳에서 함께 살다',
  'see in': '누군가가 무엇을 좋아하는지 이해하다',
  'step up': '활동이나 노력의 정도를 늘리다',
  'throw in': '대화에 말이나 질문을 덧붙이다',
  'carry on': '하던 일을 멈추지 않고 계속하다',
  'carry out': '지시받거나 계획한 일을 실행하다',
  'do without': '필요한 것이 없어도 일을 해내다',
  'go by': '이동하면서 어떤 곳을 지나가다',
  'come by': '구하기 힘든 것을 손에 넣다',
  'come out': '숨겨졌던 사실이 알려지다',
  'come with': '물건에 다른 것이 함께 딸려 오다',
  'keep to': '정한 양이나 한도를 넘지 않다',
  'write down': '잊지 않도록 글로 적다',
  'set against': '한 대상을 다른 대상과 비교하다',
  'read out': '글이나 숫자를 다른 사람이 듣도록 읽다',
  'add up': '수나 금액을 더해 합계를 내다',
  'grow up': '아이에서 성인으로 자라다',
  'step in': '문제를 막거나 해결하려고 개입하다',
  'go under': '사업이 실패해 문을 닫다',
  'get across': '생각이나 사실을 이해시키다',
  'get at': '손이 닿기 어려운 곳에 접근하다',
  'want out': '상황이나 관계에서 벗어나고 싶어 하다',
  'give off': '빛이나 열, 냄새 등을 내다',
  'give over': '하던 행동을 그만두다',
  'put away': '나중을 위해 돈을 저축하다',
  'put back': '물건을 원래 있던 자리에 돌려놓다',
  'put by': '나중에 쓰려고 돈을 모아 두다',
  'put forth': '생각이나 계획을 제안하다',
  'put forward': '직책이나 역할의 후보로 추천하다',
  'keep down': '비용이나 수치가 오르지 않게 억제하다',
  'let out': '사람이나 동물이 밖으로 나가게 하다',
  'talk through': '계획이나 상황을 차근차근 논의하다',
  'show off': '사람이나 물건이 돋보이도록 자랑하다',
  'hold off': '일부러 일을 미루거나 늦추다',
  'hold together': '어려움 속에서도 관계나 조직을 유지하다',
  'bring down': '무언가를 쓰러뜨리거나 떨어뜨리다',
  'bring forward': '예정된 날짜나 시간을 앞당기다',
  'write up': '메모를 바탕으로 기사나 보고서를 작성하다',
  'pay back': '빌린 돈을 돌려주다',
  'pay out': '특히 큰돈을 지급하다',
  'listen in': '다른 사람의 대화를 몰래 듣다',
  'fill out': '서류의 빈칸에 필요한 정보를 적다',
  'sign up': '활동이나 과정에 참여하기로 등록하다',
  'check out': '도서관에서 책을 빌리다',
  'block out': '빛이나 소리가 들어오지 못하게 막다',
  'clean up': '장소를 깨끗하고 정돈된 상태로 만들다',
  'ring out': '크고 또렷한 소리가 울려 퍼지다',
  'bring off': '어려운 일을 성공적으로 해내다',
  'wait up': '누군가 돌아올 때까지 자지 않고 기다리다',
  'pick at': '입맛이 없어 음식을 조금씩 건드리다',
  'cry off': '하기로 한 약속이나 일을 취소하다',
  'butter up': '도움을 얻으려고 칭찬하며 비위를 맞추다',
  'clock up': '특정한 수나 양을 기록하다',
  'drum up': '지지나 관심을 모으려고 힘쓰다',
  'go before': '사안이 위원회나 법정의 심의를 받다',
  'come around': '정해진 때나 기회가 다시 돌아오다',
  'come between': '두 사람이나 집단의 관계를 갈라놓다',
  'leave off': '하던 일을 멈추다',
  'leave over': '과거의 것이 아직 남아 있다',
  'move along': '일이 계속 진행되거나 발전하다',
  'live on': '정해진 돈으로 생활하다',
  'pay for': '물건이나 서비스를 사려고 돈을 내다',
  'pay into': '계좌나 기금에 돈을 납입하다',
  'walk out': '필요로 하는 사람이나 일을 갑자기 떠나다',
  'free up': '시간이나 자원을 쓸 수 있게 비우다',
  'break in': '다른 사람이 말하는 도중 끼어들다',
  'join up': '군대에 입대하다',
  'eat away': '조금씩 부식하거나 파괴하다',
  'drop away': '땅이 갑자기 아래로 가파르게 낮아지다',
  'save up': '나중에 쓰려고 돈을 모으다',
  'club together': '여럿이 돈을 조금씩 모으다',
  'blow out': '입으로 불어 불꽃을 끄다',
  'ring back': '상대에게 다시 전화하다',
  'kick back': '편히 쉬며 긴장을 풀다',
  'cloud over': '표정이 어두워지며 걱정이나 슬픔을 드러내다',
  'wash away': '물이나 비가 무언가를 휩쓸어 가다',
  'dig around': '무언가를 찾으려고 안을 이리저리 뒤지다',
  'shell out': '마지못해 큰돈을 지출하다',
  'enter into': '계약이나 합의의 당사자가 되다',
  'pour into': '많은 돈이나 노력을 쏟아붓다',
  'lead to': '어떤 결과가 생기게 하다',
  'trade in': '헌 물건을 새 물건값의 일부로 내놓다',
  'fall away': '붙어 있던 부분이 떨어져 나가다',
  'pull down': '일해서 특정한 액수의 돈을 벌다',
  'clear up': '문제나 의문을 해결하다',
  'trade on': '특징이나 신뢰를 이용해 이익을 얻다',
  'strike down': '법원이 법이나 계약을 무효로 하다',
  'tone down': '표현이나 강도를 누그러뜨리다',
  'pack up': '장비를 챙기고 일을 마치다',
  'round off': '일을 만족스럽게 마무리하다',
  'split up': '연인이나 부부가 헤어지다',
  'plant out': '어린 식물을 화분에서 땅으로 옮겨 심다',
  'double up': '두 사람이나 가족이 한 공간을 함께 쓰다',
  'square up': '맞서 싸울 자세를 취하다',
  'splash out': '비싼 물건에 큰돈을 쓰다',
  'last out': '필요한 기간이 끝날 때까지 버티다',
  'provide for': '생활에 필요한 것을 마련해 부양하다',
  'pass on': '비용을 다른 사람에게 떠넘기다',
  'hit upon': '생각이나 해답을 우연히 떠올리다',
  'hit with': '불쾌하거나 힘든 일을 겪게 하다',
  'lie behind': '결정이나 행동의 진짜 원인이 되다',
  'lie with': '책임이나 결정권이 누군가에게 있다',
  'credit with': '성과가 누군가의 공이라고 인정하다',
  'strike on': '생각이나 해답을 우연히 찾아내다',
  'gather up': '흩어진 물건을 한데 모으다',
  'shut off': '기계나 전원이 꺼져 작동을 멈추다',
  'shout down': '큰 소리로 상대의 말을 들리지 않게 막다',
  'rush through': '공식 절차를 서둘러 통과시키다',
  'knock up': '필요한 것을 급히 만들어 내다',
  'double back': '왔던 방향으로 되돌아가다',
  'weigh into': '토론에 끼어들어 강하게 의견을 말하다',
  'weigh on': '걱정이나 부담으로 마음을 짓누르다',
  'string together': '여러 내용을 순서 있게 이어 붙이다',
  'think through': '사실과 결과를 빠짐없이 깊이 생각하다',
  'crop up': '문제나 일이 뜻밖에 생기다',
  'settle in': '오래 머물 곳에 편안히 자리를 잡다',
  'rise above': '어렵거나 불쾌한 상황을 이겨 내다',
  'hang up': '통화를 끝내고 전화를 끊다',
  'hunt down': '오랫동안 찾아 끝내 발견하다',
  'bump into': '누군가를 우연히 마주치다',
  'measure out': '큰 양에서 필요한 만큼을 재어 덜다',
  'stick by': '어려운 때에도 계속 지지하다',
  'slip up': '부주의로 실수하다',
  'hammer out': '오랜 논의 끝에 합의를 만들어 내다',
  'settle up': '서로 내야 할 돈을 정산하다',
  'lean on': '도움이나 지지를 얻으려고 의지하다',
  'link up': '컴퓨터나 시스템을 서로 연결하다',
  'narrow down': '가능성이나 선택지의 수를 줄이다',
  'soak in': '장소의 분위기나 느낌을 충분히 즐기다',
  'lap up': '무언가를 무척 즐기며 받아들이다',
  'chip in': '여럿이 돈을 조금씩 보태다',
  'rack up': '많은 수나 양을 기록하다',
  'chew up': '씹거나 거칠게 다뤄 망가뜨리다',
  'sniff out': '숨은 문제나 사실을 찾아내다',
  'identify with': '다른 사람의 감정을 이해하고 공감하다',
  'buckle up': '차량에서 안전벨트를 매다',
  'conjure up': '느낌이나 기억을 떠올리게 하다',
  'lash out': '비싼 물건에 큰돈을 쓰다',
  'chime in': '대화에 끼어들어 한마디 보태다',
  'chuck in': '하던 일이나 활동을 그만두다',
  'ladle out': '국자로 음식이나 액체를 떠서 나누어 주다',
  'rake in': '많은 돈을 벌어들이다',
  'rig up': '있는 재료로 장비를 임시로 만들다',
  'shack up': '연인과 한집에서 함께 살다',
  'simmer down': '흥분이나 화를 가라앉히다',
}

function normalizeDictionaryEnding(value: string): string {
  return value
    .normalize('NFKC')
    .replace(/\s+/gu, ' ')
    .trim()
    .replace(/[.!?]+$/gu, '')
    .replace(/하기 위해서(?:입니다|요)?$/u, '하다')
    .replace(/하기 위해$/u, '하다')
    .replace(/기 위해서(?:입니다|요)?$/u, '다')
    .replace(/기 위해$/u, '다')
    .replace(/하는 데 사용됩니다$/u, '할 때 쓰는 말이다')
    .replace(/하는 것입니다$/u, '하다')
    .replace(/하는 것이다$/u, '하다')
    .replace(/하는 것은$/u, '하다')
    .replace(/하는 것$/u, '하다')
    .replace(/하게 되는 것이다$/u, '하게 되다')
    .replace(/해야 할 것이다$/u, '하다')
    .replace(/해야 합니다$/u, '하다')
    .replace(/하세요$/u, '하다')
    .replace(/합니다$/u, '하다')
    .replace(/됩니다$/u, '되다')
    .replace(/있습니다$/u, '있다')
    .replace(/없습니다$/u, '없다')
    .replace(/것입니다$/u, '것이다')
    .replace(/입니다$/u, '이다')
    .replace(/당신/gu, '자신')
}

export function readerPhrasalVerbMeanings(
  item: Pick<PhrasalVerbItem, 'phrasalVerb' | 'meaningKo'>,
): string[] {
  const correction = READER_GLOSS_CORRECTIONS[item.phrasalVerb]
  if (correction) return [correction]
  return [...new Set(item.meaningKo
    .map(normalizeDictionaryEnding)
    .filter((meaning) => meaning.length > 0))]
}

export function hasReaderGlossCorrection(phrase: string): boolean {
  return Object.hasOwn(READER_GLOSS_CORRECTIONS, phrase)
}
